### PR TITLE
Add a constant module

### PR DESCRIPTION
**Pull request by xldenis**
I wanted to use this for code generation but I realized there was no mechanism to generate constant operands. 

For now the module just has helpers for basic numerical types, I think it's pretty reasonable to expand this to arrays and structs but should this cover all the constant values?

### CODE REVIEW

**Comment by cocreature** [comment]
Hey, thanks for your contribution! `llvm-hs-irbuilder` has been merged into [llvm-hs-pure](https://github.com/llvm-hs/llvm-hs) and development should continue in that repository. It would be great if you could resubmit your PR there. If you are having trouble with that, let me know and I can do it for you.

**Comment by sdiehl** [comment]
@xldenis Yes looks great.

**Comment by sdiehl** [comment]
Might want to add it to the [default exports](https://github.com/llvm-hs/llvm-irbuilder/blob/master/src/LLVM/IRBuilder.hs) as well so we don't have another module to import.

**Comment by xldenis** [comment]
Oh awesome! I wasn't sure if the migration had happened yet because I the issue was still open last night! I'll push a PR over there.

**Pull request closed without merging**
